# Generated by Django 3.0.7 on 2020-10-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(related_name='groups', to='bot.BotUser'),
        ),
    ]
