# Generated by Django 3.0.7 on 2020-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201021_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
