# Generated by Django 3.0.7 on 2020-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20201021_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='github_login',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
