# Generated by Django 3.0.7 on 2020-10-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bot', '0005_githubrepository'), ('bot', '0006_submission'), ('bot', '0007_auto_20201023_2223'), ('bot', '0008_auto_20201024_1857'), ('bot', '0009_auto_20201024_1950')]

    dependencies = [
        ('bot', '0004_botuser_github_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('url', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='bot.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField(db_index=True)),
                ('task_id', models.IntegerField(db_index=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objectkey', models.TextField()),
                ('pull_url', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotUser')),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.GithubRepository')),
                ('assignment_type', models.TextField(default='pending')),
                ('gist_url', models.TextField(default='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment_type', 'assignment_id', 'task_id'), name='unq_type_assignment_task'),
        ),
        migrations.CreateModel(
            name='AssignmentGistCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gist_id', models.TextField()),
                ('task_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignmentgistcache',
            constraint=models.UniqueConstraint(fields=('gist_id', 'task_id'), name='gist_id_task_id'),
        ),
    ]
