# Generated by Django 3.0.7 on 2020-10-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_githubrepository_squashed_0009_auto_20201024_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assignment_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gist_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='pull_url',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bot.Submission')),
            ],
        ),
    ]
