# Generated by Django 3.1.2 on 2020-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20201025_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionevent',
            name='payload',
            field=models.JSONField(null=True),
        ),
    ]
