# Generated by Django 3.1.2 on 2020-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20201025_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
