# Generated by Django 3.1.2 on 2020-11-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_githubtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='git_ref',
            field=models.TextField(null=True),
        ),
    ]
