# Generated by Django 3.1.2 on 2020-11-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='bot.botuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='real_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gist_url',
            field=models.TextField(null=True),
        ),
    ]
